apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
- files:
  - ca-bundle.crt=conf/mitmproxy-ca-crt.pem
  name: user-ca-bundle
  namespace: openshift-config
  options:
    disableNameSuffixHash: true

resources:
- cluster-proxy.yaml
