apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
- files:
  - mitmproxy-ca.pem=conf/mitmproxy-ca.pem
  name: mitmproxy-ca-cert

namespace: mitmproxy

resources:
- mitmproxy-deployment.yaml
- mitmproxy-namespace.yaml
- mitmproxy-service.yaml
